rt -b -q 'run.C("Sherpa","a")'
rt -b -q 'run.C("Sherpa","d")'
rt -b -q 'run.C("Sherpa","e")'
# rt -b -q 'run.C("MG","a")'
# rt -b -q 'run.C("MG","d")'
# rt -b -q 'run.C("MG","e")'
# rt -b -q 'run.C("SherpaScaleUp","a")'
# rt -b -q 'run.C("SherpaScaleUp","d")'
# rt -b -q 'run.C("SherpaScaleUp","e")'
# rt -b -q 'run.C("SherpaScaleDown","a")'
# rt -b -q 'run.C("SherpaScaleDown","d")'
# rt -b -q 'run.C("SherpaScaleDown","e")'
